[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_EXPERIMENTAL_DISABLE_BLOBS = "true"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_next/image"
  query = { url = ":url", w = ":width", q = ":quality" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

[[redirects]]
  from = "/_ipx/*"
  query = { url = ":url", w = ":width", q = ":quality" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
